name: Add PR Number To Changelog Files

on:
  pull_request:
    types: [ opened, synchronize ]
    branches-ignore:
      - "main"
    paths:
      - "projects/*/*/changelog/*" # projects/<project-type>/<project>/changelog/<changelog-files>
      - "!projects/*/*/changelog/.gitkeep"

jobs:
  echo-test:
    runs-on: ubuntu-latest
    env:
      PR_NUM: ${{ github.event.number }}
    steps:
      - name: Echo some data
        run: |
          echo "Testing: "
          echo "${{ toJson( github.event ) }}"
