name: Add PR number to changelogs

on:
  pull_request:
    types: [ opened, synchronize ]
    # paths:
    #   - "projects/*/*/changelog/*" # projects/<project-type>/<project>/changelog/<changelog-files>

jobs:
  changed-files:
    name: Detect changed files
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changed-files
  
  add-pr-num:
    name: Add PR number to changelogs
    runs-on: ubuntu-latest
    steps:
      
      - name: Debug, echo event data
        run: |
          echo "github event: "
          echo "${{ toJson( github.event ) }}"
