name: Add PR number to changelogs

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - "projects/*/*/changelog/**" # projects/<project-type>/<project>/changelog/<changelog-files>

jobs:
  add-pr-num:
    name: Add PR number to changelogs
    runs-on: ubuntu-latest
    steps:
      - name: Detect changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            any:
              - added|modified: '**'

      - name: Debug, echo some data
        run: |
          echo "Changed Files: ${{ steps.filter.outputs.any_files }}"
          echo "github.event.number: ${{ github.event.number }}"
