name: Add PR number to changelogs

on:
  pull_request:
    types: [ opened, synchronize ]
    # paths:
    #   - "projects/*/*/changelog/*" # projects/<project-type>/<project>/changelog/<changelog-files>

jobs:
  add-pr-num:
    name: Add PR number to changelogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
        
      - name: Echo event data
        run: |
          echo "github event: "
          echo "${{ toJson( github.event ) }}"
