name: Add PR number to changelogs

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - "projects/*/*/changelog/**" # projects/<project-type>/<project>/changelog/<changelog-files>

jobs:
  add-pr-num:
    name: Add PR number to changelogs
    runs-on: ubuntu-latest
    steps:
      - name: Detect changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            changelog:
              - added|modified: 'projects/*/*/changelog/!(.gitkeep)'

      - uses: actions/checkout@v3
      # Todo: ./.github/actions/tool-setup ?

      - name: Write PR number to changelogs
        if: ${{ steps.filter.outputs.changelog == 'true' }}
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          echo "::group::Found added or modified changelog files"
          echo "${{ steps.filter.outputs.changelog_files }}" | tr ' ' '\n'
          echo "::endgroup::"
          echo "${{ steps.filter.outputs.changelog_files }}" | xargs -n 1 .github/scripts/add-pr-num-to-changelog.py $PR_NUM
          git status
          echo "todo: commit if changed files at this point"

      - name: Debug, echo some data
        run: |
          echo "github.event.number: ${{ github.event.number }}"
          echo "Python version: $( python3 --version )"
