name: Add PR Number To Changelog Files

on:
  push:
    branches: [ main ]
    paths:
      - "projects/*/*/changelog/*" # projects/<project-type>/<project>/changelog/<changelog-files>

jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo some data
        run: |
          echo "github.event: "
          echo "${{ toJson( github.event ) }}"
  # add-pr-num:
  #   runs-on: ubuntu-latest
  #   env:
  #     PR_NUM: ${{ github.event.number }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: List files
  #       run: echo Listing post-checkout files && ls -al
