name: Add PR number to changelogs

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - "projects/*/*/changelog/**" # projects/<project-type>/<project>/changelog/<changelog-files>

jobs:
  add-pr-num:
    name: Add PR number to changelogs
    runs-on: ubuntu-latest
    steps:
      - name: Detect changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            changelog:
              - added|modified: 'projects/*/*/changelog/!(.gitkeep)'

      - uses: actions/checkout@v3
      # Todo: ./.github/actions/tool-setup ?

      - name: Write PR number to changelogs
        if: ${{ steps.filter.outputs.changelog == 'true' }}
        id: write
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          echo "::group::Found added or modified changelog files in this PR:"
          echo "${{ steps.filter.outputs.changelog_files }}" | tr ' ' '\n'
          echo "::endgroup::"
          echo "${{ steps.filter.outputs.changelog_files }}" | xargs -n 1 .github/scripts/add-pr-num-to-changelog.php $PR_NUM
          echo "::set-output name=MODIFIED::$( if [ -n "$( git status --porcelain )" ]; then echo "true"; else echo "false"; fi )"

      - name: Commit modified changelog files
        if: steps.write.outputs.MODIFIED == 'true'
        run: |
          echo "Todo the committing stuff here..."
          git status

      - name: Debug, echo some data
        run: |
          echo "github.event.number: ${{ github.event.number }}"
