name: k6 Tests for Jetpack Staging Test Sites
# Runs k6 tests for the same sites updated by `update-jetpack-staging-sites.yml`.

on:
  workflow_dispatch:
  # Todo: put this on an interval.

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      JETPACKSTAGING_K6_USERNAME: ${{ secrets.JETPACKSTAGING_K6_USERNAME }}
      JETPACKSTAGING_K6_PASSWORD: ${{ secrets.JETPACKSTAGING_K6_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Run k6 frontend tests
        run: k6 run .github/files/jetpack-staging-sites/k6-frontend.js

      - name: Run k6 backend tests
        run: k6 run .github/files/jetpack-staging-sites/k6-backend.js
