name: Simple Shell Script Test

on: push

jobs:
  
  run-shell-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo files
        uses: actions/checkout@v3.0.0

      - name: run-the-script
        shell: bash
        run: ./.github/scripts/simple-shell.sh 'samiff'
