name: Simple Shell Commands Test # Workflow name.

on: [ push ] # The name(s) of the GitHub event that triggers the workflow.

jobs: # A workflow consists of one or more jobs.
  echo-date: # The custom name of a job.
    runs-on: ubuntu-latest # The type of machine to run the job on.
    steps: # Steps/tasks to complete in the job.
      - name: Echo out date # A name for the step to display on GitHub.
        run: "echo Current system date: $( date )" # Run command-line programs using runner's shell.
  echo-versions: # Another job.
    runs-on: ubuntu-latest
    steps:  
      - name: Echo git version
        run: git --version
      - name: Echo node/npm versions multiline with pipe
        run: |
          node -v
          npm -v
  python-commands: # bash is default shell, but can also process commands with python for example.
    runs-on: ubuntu-latest
    steps:
      - name: Python print platform cpu
        run: |
          import platform
          print( platform.processor() )
        shell: python # Inform GH to use python for run command.
  windows-commands:
    runs-on: windows-latest # Job will run on Windows platform in parallel by default.
    needs: [ "echo-date" ] # Make this job run in series after the specified jobs.
    steps:
      - name: PowerShell print current dir
        run: Get-Location
      - name: bash on Windows print current dir
        run: pwd
        shell: bash # Powershell is default for Windows, so need to specify bash here.
