name: Simple Shell Commands Test # Workflow name.

on: [ push ] # The name(s) of the GitHub event that triggers the workflow.

jobs: # A workflow consists of one or more jobs.
  echo-date: # The custom name of a job.
    runs-on: ubuntu-latest # The type of machine to run the job on.
    steps: # Steps/tasks to complete in the job.
      - name: Echo out date # A name for the step to display on GitHub.
        run: "echo Current system date $( date )" # Run command-line programs using runner's shell.
  echo-versions:
    runs-on: ubuntu-latest
    steps:  
      - name: Echo git version
        run: git --version
      - name: Echo node/npm versions multiline with pipe
        run: |
          node -v
          npm -v
