# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
# https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event

name: Test Workflow

on:
  workflow_dispatch:
    
jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Config
        env:
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: Execute script
        shell: bash
        env:
          TC_UPDATEJETPACKSTAGING_SSH_KEY: ${{ secrets.TC_UPDATEJETPACKSTAGING_SSH_KEY }}
        run: ./.github/scripts/test-script.sh
